name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17 and Maven
      uses: s4u/setup-maven-action@v1.7.0
      with:
        checkout-fetch-depth: 0
        java-version: 8
        java-distribution: temurin
        maven-version: 3.8.7

    - name: Compilando...
      run: mvn compile

    - name: Testes das Classes
      run: |
        mvn test -Dtest=AdministratorTest test -Dsurefire.failIfNoSpecifiedTests=false;
        mvn test -Dtest=eWalletTest test;
        mvn test -Dtest=PlayerTest test;
        mvn test -Dtest=PlaygroundOwnerTest test;
        mvn test -Dtest=PlayGroundScheduleTest test;
        mvn test -Dtest=PlaygroundTest test;
        EXIT_CODE=$?
      if: always()
